# Generated by Django 5.0.6 on 2024-07-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='popupstore',
            name='latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='popupstore',
            name='longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
