# Generated by Django 5.0.4 on 2024-07-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popplace', '0002_popupstore_latitude_popupstore_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateTimeField(default='<function now at 0x000002AD6EEF49A0>'),
        ),
    ]
