# Generated by Django 5.0.4 on 2024-07-02 16:16

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popplace', '0005_alter_reservation_reservation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_date',
        ),
        migrations.AddField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='time',
            field=models.TimeField(default=datetime.time(16, 16, 1, 519122)),
            preserve_default=False,
        ),
    ]
