# Generated by Django 5.0.4 on 2024-07-02 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popplace', '0006_remove_reservation_reservation_date_reservation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
    ]
