# Generated by Django 5.0.4 on 2024-07-02 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popplace', '0007_remove_reservation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
