# Generated by Django 5.0.6 on 2024-07-02 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popplace', '0010_rename_tag_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='popupstore',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='popplace.category'),
        ),
        migrations.AddField(
            model_name='popupstore',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='popplace.location'),
        ),
    ]
