# Generated by Django 5.0.6 on 2024-07-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popplace', '0011_popupstore_categorie_popupstore_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='popupstore',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='popupstore',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
