# Generated by Django 5.0.6 on 2024-07-04 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popplace', '0012_popupstore_end_date_popupstore_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='popupstore',
            old_name='categorie',
            new_name='category',
        ),
    ]
