# Generated by Django 5.0.6 on 2024-07-04 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popplace', '0013_rename_categorie_popupstore_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popupstore',
            name='operating_period',
        ),
    ]
