# Generated by Django 5.0.6 on 2024-07-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popplace', '0017_alter_review_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='popupstore',
            name='homepage',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='popupstore',
            name='sns',
            field=models.URLField(blank=True, null=True),
        ),
    ]
