# Generated by Django 5.0.6 on 2024-07-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popplace', '0018_popupstore_homepage_popupstore_sns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='sustainability_rating',
            field=models.BooleanField(default=True),
        ),
    ]
