# Generated by Django 5.0.6 on 2024-07-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popplace', '0020_alter_review_sustainability_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='positive_rating',
            field=models.CharField(choices=[('yes', '예'), ('no', '아니오')], default='yes', max_length=3),
        ),
    ]
