# Generated by Django 4.2.13 on 2024-07-04 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_stamp_description_reservation_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stamp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stamps', to=settings.AUTH_USER_MODEL),
        ),
    ]
