# Generated by Django 4.2.13 on 2024-07-05 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0005_category_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popupstore',
            name='category',
        ),
        migrations.RemoveField(
            model_name='popupstore',
            name='location',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='popup_store',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.permission'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='PopupStore',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
